name: Java CI with Maven (verifies code style and dry run to check all the step definitions exists)

on:
  pull_request:
    branches: [ master, develop, feature/*, release/* ]

jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B compile --file pom.xml -PdryRun checkstyle:check test
